language: python
python:
    - "2.7"
install: pip install -r requirements.txt
sudo: required
before_install:
    - sudo apt install python-logilab-common
    - pip install pytest pytest-cov
script: pytest
